apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-configmap
data:
  application.properties: |-
    welcome.message: Welcome from K8S!
    message: Welcome to default message from K8s!!

---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: spring-configmap-secret
# type: Opaque
# data:
#   welcome.topSecret: dG9wIGxldmVsIHNlY3JldHM=