apiVersion: v1
kind: Service
metadata:
  name: spring-configmap
spec:
  selector:
    app: spring-configmap
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-configmap
  template:
    metadata:
      labels:
        app: spring-configmap
    spec:
      serviceAccountName: spring-configmap-sa
      containers:
      - name: spring-configmap
        image: spring-configmap
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /config
            name: spring-configmap
          # - mountPath: /etc/secret
          #   name: spring-configmap-secret

      volumes:
        - name: spring-configmap
          configMap:
              name: spring-configmap
        # - name: spring-configmap-secret
        #   secret:
        #       secretName: spring-configmap-secret

