# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
#  namespace: default
  name: spring-configmap-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-configmap-sa
#  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-configmap-role-binding
#  namespace: default
subjects:
  - kind: ServiceAccount
    name: spring-configmap-sa
#    namespace: default
roleRef:
  kind: ClusterRole
  name: spring-configmap-reader
  apiGroup: rbac.authorization.k8s.io

